// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: log.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLogEntry = `-- name: CreateLogEntry :one
INSERT INTO log (id, created_at, updated_at, requester, request, result)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2, $3
)
RETURNING id, created_at, updated_at, requester, request, result
`

type CreateLogEntryParams struct {
	Requester string
	Request   string
	Result    bool
}

func (q *Queries) CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLogEntry, arg.Requester, arg.Request, arg.Result)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Requester,
		&i.Request,
		&i.Result,
	)
	return i, err
}

const deleteLogEntryByID = `-- name: DeleteLogEntryByID :exec
DELETE FROM log WHERE id = $1
`

func (q *Queries) DeleteLogEntryByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLogEntryByID, id)
	return err
}

const getAllLogEntries = `-- name: GetAllLogEntries :many
SELECT id, created_at, updated_at, requester, request, result FROM log
`

func (q *Queries) GetAllLogEntries(ctx context.Context) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getAllLogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Requester,
			&i.Request,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogEntryByID = `-- name: GetLogEntryByID :one
SELECT id, created_at, updated_at, requester, request, result FROM log WHERE id = $1
`

func (q *Queries) GetLogEntryByID(ctx context.Context, id uuid.UUID) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogEntryByID, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Requester,
		&i.Request,
		&i.Result,
	)
	return i, err
}

const getLogEntryByRequester = `-- name: GetLogEntryByRequester :one
SELECT id, created_at, updated_at, requester, request, result FROM log WHERE requester = $1
`

func (q *Queries) GetLogEntryByRequester(ctx context.Context, requester string) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogEntryByRequester, requester)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Requester,
		&i.Request,
		&i.Result,
	)
	return i, err
}

const getLogEntryByResult = `-- name: GetLogEntryByResult :one
SELECT id, created_at, updated_at, requester, request, result FROM log WHERE result = $1
`

func (q *Queries) GetLogEntryByResult(ctx context.Context, result bool) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogEntryByResult, result)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Requester,
		&i.Request,
		&i.Result,
	)
	return i, err
}
