// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Log struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Requester string
	Request   string
	Result    bool
}

type Preset struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Colors    []int64
}
