// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPreset = `-- name: CreatePreset :one
INSERT INTO presets (id, created_at, updated_at, name, color1, color2)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2, $3
)
RETURNING id, created_at, updated_at, name, color1, color2
`

type CreatePresetParams struct {
	Name   string
	Color1 int64
	Color2 int64
}

func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, createPreset, arg.Name, arg.Color1, arg.Color2)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Color1,
		&i.Color2,
	)
	return i, err
}

const deletePresetByID = `-- name: DeletePresetByID :exec
DELETE FROM presets WHERE id = $1
`

func (q *Queries) DeletePresetByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePresetByID, id)
	return err
}

const getAllPresets = `-- name: GetAllPresets :many
SELECT id, created_at, updated_at, name, color1, color2 FROM presets
`

func (q *Queries) GetAllPresets(ctx context.Context) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, getAllPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preset
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Color1,
			&i.Color2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPresetByID = `-- name: GetPresetByID :one
SELECT id, created_at, updated_at, name, color1, color2 FROM presets WHERE id = $1
`

func (q *Queries) GetPresetByID(ctx context.Context, id uuid.UUID) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPresetByID, id)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Color1,
		&i.Color2,
	)
	return i, err
}
