// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presets.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPreset = `-- name: CreatePreset :one
INSERT INTO presets (id, created_at, updated_at, name, colors)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2
)
RETURNING id, created_at, updated_at, name, colors, protected
`

type CreatePresetParams struct {
	Name   string
	Colors []int64
}

func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, createPreset, arg.Name, pq.Array(arg.Colors))
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		pq.Array(&i.Colors),
		&i.Protected,
	)
	return i, err
}

const deletePresetByID = `-- name: DeletePresetByID :exec
DELETE FROM presets WHERE id = $1
`

func (q *Queries) DeletePresetByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePresetByID, id)
	return err
}

const getAllPresets = `-- name: GetAllPresets :many
SELECT id, created_at, updated_at, name, colors, protected
FROM presets
ORDER BY protected DESC
`

func (q *Queries) GetAllPresets(ctx context.Context) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, getAllPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preset
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			pq.Array(&i.Colors),
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPresetByID = `-- name: GetPresetByID :one
SELECT id, created_at, updated_at, name, colors, protected FROM presets WHERE id = $1
`

func (q *Queries) GetPresetByID(ctx context.Context, id uuid.UUID) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPresetByID, id)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		pq.Array(&i.Colors),
		&i.Protected,
	)
	return i, err
}
